### ISSUE TITLE
OpenVINO conversion failure

### ISSUE THREAD

**Issue by wsarce** [luxonis/blobconverter#14]
I have a Tensorflow model that I've been able to compile using OpenVINO 2021.3 mo_tf.py.  I've been trying every method of compilation for MyriadX.  I've tried both the CLI and Python script route, which returned:
`requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://luxonis.com:8080/compile?version=2021.3`

Trying with the online converter, I get the following error:
`Encountered unknown input type of a loop v5::Loop StatefulPartitionedCall/sequential_1/lstm/PartitionedCall/while (StatefulPartitionedCall/sequential_1/lstm/PartitionedCall/strided_slice[0]:i32{}, StatefulPartitionedCall/sequential_1/lstm/PartitionedCall/while/ExecutionConditionValue/Output_0/Data__const[0]:boolean{}, StatefulPartitionedCall/sequential_1/lstm/PartitionedCall/time/Output_0/Data__const[0]:i32{}, StatefulPartitionedCall/sequential_1/lstm/zeros/Broadcast[0]:f16{1,30}, StatefulPartitionedCall/sequential_1/lstm/zeros_1/Broadcast[0]:f16{1,30}, StatefulPartitionedCall/sequential_1/lstm/PartitionedCall/strided_slice[0]:i32{}, StatefulPartitionedCall/sequential_1/lstm/PartitionedCall/transpose[0]:f16{30,1,12800}) -> (f16{30,1,30}) at index 0`

Additionally, the console output consistently generates the same message in a long loop from all methods:
`[myriad_compile] usb_find_device_with_bcd:266\tLibrary has not been initialized when loaded\u001b[0m\n\u001b[35mE: [xLinkUsb] [    939705] [myriad_compile] usb_find_device_with_bcd:266\tLibrary has not been initialized when loaded\u001b[0m\n\u001b[35mE: [xLinkUsb] [    939705]`

Is there anything that I'm missing in this process?  The model is a VGG19 for transfer learning with a trained CNN and an input shape of [1, 30, 160, 160, 3].

**Comment by wsarce** [comment]
When trying it with the deprecated web converter, I get the following error:
`Cannot create ShapeOf layer StatefulPartitionedCall/sequential_1/lstm/PartitionedCall/Shape id:104`

Any ideas on how to clear this error? If the model was able to compile with OpenVINO, should it be fully compatible with the MyriadX?

**Comment by VanDavv** [comment]
@wsarce which compilation params are you using? is the compilation successful using a local OpenVINO installation?

VGG19 should be compatible with OpenVINO, so if the architecture was not changed and no custom layers were added the conversion should be successful

**Comment by wsarce** [comment]
@VanDavv I used the following parameters to compile to IR format:

`python "C:\Program Files (x86)\Intel\openvino_2021.3.394\deployment_tools\model_optimizer\mo_tf.py" --saved_model_dir "{path_to_model_dir}" --input_shape=[1,30,160,160,3] --data_type=FP16 --mean_values=[127.5,127.5,127.5] --scale_values=[255,255,255] --static_shape --log_level=DEBUG`

This does generate IR files, but the Myriad blob generation fails.  The command I tried on my local machine was:

`"C:\Program Files (x86)\Intel\openvino_2021.3.394\deployment_tools\tools\compile_tool\compile_tool.exe" -m "{saved_model_path}\saved_model.xml" -d MYRIAD `

Which results in the same error as the web converter.  The model adds two TimeDistributed layers: one wrapping the VGG19 to allow a 30 image input to the model which feeds into a TimeDistributed Dense layer.  Could it be the TimeDistributed layers?

**Comment by wsarce** [comment]
The Loop5 instruction is only supported on CPU at this time.  I assume TimeDistributed is using this instruction.

https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Encountered-unknown-input-type-of-a-loop-v5-Loop/m-p/1289475#M24089
