### ISSUE TITLE
 "Cannot create Gather layer Gather_169525 id:338 from unsupported opset: opset7\n",

### ISSUE THREAD

**Issue by tuantran23012000** [luxonis/blobconverter#16]
I had converted model.pth to model.onnx with opset10, then I used openvino to convert model.onnx to 2 files: .xml and .bin. But, when I converted from .xml and .bin to IR, I had issue "Cannot create Gather layer Gather_169525 id:338 from unsupported opset: opset7\n"

**Comment by trananhtuan23012000** [comment]
model.pth to model.onnx 
import sys
import torch.onnx
#import torchvision
import torch
from torch.autograd import Variable
sys.path.append(".")
import os
from utility import get_kernel, parse_model_name
from model_lib.MiniFASNet import MiniFASNetV1, MiniFASNetV2,MiniFASNetV1SE,MiniFASNetV2SE
model_path="D:/tuan/AI/CODE/Silent-Face-Anti-Spoofing/resources/anti_spoof_models/4_0_0_80x80_MiniFASNetV1SE.pth"
MODEL_MAPPING = {
    'MiniFASNetV1': MiniFASNetV1,
    'MiniFASNetV2': MiniFASNetV2,
    'MiniFASNetV1SE':MiniFASNetV1SE,
    'MiniFASNetV2SE':MiniFASNetV2SE
}
model_name = os.path.basename(model_path)
h_input, w_input, model_type, _ = parse_model_name(model_name)
kernel_size = get_kernel(h_input, w_input,)
device = torch.device("cuda:{}".format(0)
                                   if torch.cuda.is_available() else "cpu")
model = MODEL_MAPPING[model_type](conv6_kernel=kernel_size).to(device)
print(h_input,w_input)
#model = AntiSpoofPredict(0)
dummy_input = Variable(torch.randn(1, 3, h_input, w_input))
state_dict = torch.load(model_path,map_location=device)
keys = iter(state_dict)
first_layer_name = keys.__next__()
if first_layer_name.find('module.') >= 0:
    from collections import OrderedDict
    new_state_dict = OrderedDict()
    for key, value in state_dict.items():
        name_key = key[7:]
        new_state_dict[name_key] = value
    model.load_state_dict(new_state_dict)
else:
    model.load_state_dict(state_dict)
#model.load_state_dict(state_dict)
print(model)
batch_size=3

torch.onnx.export(model,               # model being run
                  dummy_input,                         # model input (or a tuple for multiple inputs)
                  "4_0_0_80x80_MiniFASNetV1SE.onnx",   # where to save the model (can be a file or file-like object)
                  #export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=10,          # the ONNX version to export the model to
                  #do_constant_folding=True,  # whether to execute constant folding for optimization
                  #input_names = ['input'],   # the model's input names
                  #output_names = ['output'], # the model's output names
                  #dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                  #              'output' : {0 : 'batch_size'}})
)

**Comment by trananhtuan23012000** [comment]
Then I run "python mo.py --input_model D:/tuan/AI/CODE/Silent-Face-Anti-Spoofing/src/4_0_0_80x80_MiniFASNetV1SE.onnx"

**Comment by trananhtuan23012000** [comment]
Finally, I run script
xmlfile = "D:/tuan/AI/CODE/openvino/model-optimizer/4_0_0_80x80_MiniFASNetV1SE.xml"
binfile = "D:/tuan/AI/CODE/openvino/model-optimizer/4_0_0_80x80_MiniFASNetV1SE.bin"


import blobconverter
blob_path = blobconverter.from_openvino(
    xml=xmlfile,
    bin=binfile,
    data_type="FP16",
    shaves=4,
)
from google.colab import files
files.download(blob_path)

**Comment by trananhtuan23012000** [comment]
Full issue
Downloading C:\Users\Tuan\.cache\blobconverter\4_0_0_80x80_MiniFASNetV1SE_openvino_2021.3_4shave.blob...
{
    "exit_code": 1,
    "message": "Command failed with exit code 1, command: /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/myriad_compile -m /tmp/blobconverter/46dd86e0f26e41dc9cf4546dee6c5351/4_0_0_80x80_MiniFASNetV1SE/FP32/4_0_0_80x80_MiniFASNetV1SE.xml -o /tmp/blobconverter/46dd86e0f26e41dc9cf4546dee6c5351/4_0_0_80x80_MiniFASNetV1SE/FP32/4_0_0_80x80_MiniFASNetV1SE.blob -c /tmp/blobconverter/46dd86e0f26e41dc9cf4546dee6c5351/myriad_compile_config.txt -ip U8",
    "stderr": "Cannot create Gather layer Gather_169525 id:338 from unsupported opset: opset7\n",
    "stdout": "Inference Engine: \n\tAPI version ............ 2.1\n\tBuild .................. 2021.3.0-2787-60059f2c755-releases/2021/3\n\tDescription ....... API\n"
}
Traceback (most recent call last):
  File "convert.py", line 10, in <module>
    shaves=4,
  File "C:\Program Files\Python\Python36\lib\site-packages\blobconverter\__init__.py", line 348, in from_openvino
    return compile_blob(blob_name=xml_path.stem, req_data=body, req_files=files, **kwargs)
  File "C:\Program Files\Python\Python36\lib\site-packages\blobconverter\__init__.py", line 252, in compile_blob
    response.raise_for_status()
  File "C:\Program Files\Python\Python36\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://luxonis.com:8080/compile?version=2021.3

**Comment by VanDavv** [comment]
Hi @trananhtuan23012000,

opset7 is not supported by ngraph - https://docs.openvinotoolkit.org/latest/ngraph_python_api/files.html
could you manually change all `opset7` do a different one, e.g. `opset2`?

if that doesn't help, I think your network is not convertible to MyriadX blob

**Comment by trananhtuan23012000** [comment]
Tks @VanDavv for your help. I'll try it ^_^

**Comment by VanDavv** [comment]
@tuantran23012000 any luck with your network conversion? I'm wondering if I should close this issue
