### ISSUE TITLE
"Check 'backward_compatible_check || in_out_elements_equal' failed at core/src/op/reshape.cpp:395:\nWhile validating node '

### ISSUE THREAD

**Issue by TomasMendozaHN** [luxonis/blobconverter#23]
Hello!
I have successfully converted a Yolo v3 pytorch model to OpenVINO format. However, when trying to convert it to MyriadX blob format, I get the following error:

```
python -m blobconverter --openvino-xml YOLO_V3.xml --openvino-bin YOLO_V3.bin
Downloading C:\Users\user\.cache\blobconverter\YOLO_V3_openvino_2021.4_4shave.blob...

{
    "exit_code": 1,
    "message": "Command failed with exit code 1, command: /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/myriad_compile -m /tmp/blobconverter/244035adc43c4988ba896476578c106e/YOLO_V3/FP16/YOLO_V3.xml -o /tmp/blobconverter/244035adc43c4988ba896476578c106e/YOLO_V3/FP16/YOLO_V3.blob -c /tmp/blobconverter/244035adc43c4988ba896476578c106e/myriad_compile_config.txt -ip U8",
    "stderr": "Check 'backward_compatible_check || in_out_elements_equal' failed at core/src/op/reshape.cpp:395:\nWhile validating node 'v1::Reshape Reshape_145 (LeakyRelu_143[0]:f32{1,256,4,2}, Constant_144[0]:i64{6}) -> (f32{?,?,?,?,?,?})' with friendly_name 'Reshape_145':\nRequested output shape {4,256,4,1,2,1} is incompatible with input shape Shape{1, 256, 4, 2}\n\n",
    "stdout": "Inference Engine: \n\tIE version ......... 2021.4.0\n\tBuild ........... 2021.4.0-3839-cd81789d294-releases/2021/4\n\u001b[1;33m[Warning][VPU][Config] Deprecated option was used : VPU_MYRIAD_PLATFORM\u001b[0m\n"
}

```
Could you please tell me how to fix it? I have successfully converted another OpenVINO model into MyriadX, but I'm having a lot of troubles with this model...

Thank you!! :)

**Comment by Erol444** [comment]
Hello @TomasMendozaHN, the Yolo V3 (full) is already available by the OpenVINO model zoo (in IR format - xml/bin) so you could download that directly. We also support it directly from the depthai_demo, so you could run `python3 depthai_demo.py -cnn yolo-v3` to run it directly. Also asking our ML engineer if he has any ideas about this issue.

**Comment by TomasMendozaHN** [comment]
Thank you for your quick response. I will use the model you recommend, as it's definitely the most convenient way. However i would like to know how to solve this issue for future reference.

**Comment by Erol444** [comment]
You are welcome @TomasMendozaHN . From quick search there's [this openvino](https://docs.openvinotoolkit.org/latest/omz_models_model_yolo_v3_tf.html) docs about the yolo-v3 and there are some conversion steps.
