### ISSUE TITLE
OpenVINO IR conversion fail - HTTPError: 502

### ISSUE THREAD

**Issue by Orchidaceae** [luxonis/blobconverter#24]
Hi

I'm trying to convert an OpenVINO IR of the [EfficientDet d0 network](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) that I in turn converted from TensorFlow using OpenVINO's model optimizer (version 2021.4.689) without any issues. But when I use blobconverter on the .bin and .xml files i get the following problem:

```bash
(venv) ljosefs@UTVPOOL-SE-LL02:~/Desktop/AI-KIT/depthai-tutorials-practice$ ./blob_convert.sh 
Downloading /home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/efficientdet_d0_coco17_tpu-32/saved_model_openvino_2021.4.1_4shave.blob...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/venv/lib/python3.8/site-packages/blobconverter/__main__.py", line 3, in <module>
    __run_cli__()
  File "/home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/venv/lib/python3.8/site-packages/blobconverter/__init__.py", line 483, in __run_cli__
    return from_openvino(
  File "/home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/venv/lib/python3.8/site-packages/blobconverter/__init__.py", line 388, in from_openvino
    return compile_blob(blob_name=xml_path.stem, req_data=body, req_files=files, **kwargs)
  File "/home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/venv/lib/python3.8/site-packages/blobconverter/__init__.py", line 263, in compile_blob
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://blobconverter.luxonis.com/compile?version=2021.4.1
```

calling blobconverter using this command:
```bash
python3 -m blobconverter --openvino-xml /home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/efficientdet_d0_coco17_tpu-32/saved_model.xml --openvino-bin /home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/efficientdet_d0_coco17_tpu-32/saved_model.bin --output-dir /home/ljosefs/Desktop/AI-KIT/depthai-tutorials-practice/efficientdet_d0_coco17_tpu-32 --shaves 4
```

Any idea of as to why this issue arises?

**Comment by Erol444** [comment]
Hello @Orchidaceae ,
@VanDavv  would probably be the best to advise here. The only thing I found strange is the URL `http://blobconverter.luxonis.com/compile?version=2021.4.1` - **version=2021.4.1**.
Not sure how you got that version, but server should return a useful error eg. `specified version is not valid`.
Thanks, Erik

**Comment by VanDavv** [comment]
Hi @Orchidaceae,
The error in your last message is different, it's 400 Bad Request instead of the original 502 Bad Gateway - and the former one indicate it's an issue with this specific request whereas the latter would mean that our whole server is unreachable.

Taking a look at the response, I noticed the `-9` exit code, which indicates that process was killed by the operating system - and my guess would be that it consumed too much memory. I'll investigate this further tomorrow and check system logs to confirm, but in the meantime I would advise to use local myriad compile tool, even just to check if the compilation process is correct for this network

**Comment by Orchidaceae** [comment]
I have actually already tried using the myriad compile tool for the exact network. The problem there was that it would just never end the compilation process. I let the process run for around 2h without any results. Could it be the same issue here?

**Comment by VanDavv** [comment]
Yes, this is most likely the same issue, the blobconverter is a wrapper around regular commands, so if they don't work, this tool won't successfully run either. Could you report it to [openvino repository](https://github.com/openvinotoolkit/openvino/issues)? They will likely give more details on why the compilation process takes that much time

**Comment by Orchidaceae** [comment]
I see. I have posted an [issue](https://github.com/openvinotoolkit/openvino/issues/7681) there as of the moment, let's hope they can give more insight into this problem. Anyways, thanks for the support guys @VanDavv @Erol444
