### ISSUE TITLE
[Bug] validate_nonnegative_int('"size"', file['size']) - KeyError: 'size'

### ISSUE THREAD

**Issue by Erol444** [luxonis/blobconverter#27]
Doesn't look like it's a standard conversion error (based on the exception file path).
```
  File "/app/model_compiler/openvino_2021.4/src/open_model_zoo/model_tools/_configuration.py", line 177, in deserialize
    size = validate_nonnegative_int('"size"', file['size'])
KeyError: 'size'
```
**ONNX model:** [normalize.zip](https://github.com/luxonis/blobconverter/files/7281188/normalize.zip)

**Blobconverter web app error**

![image](https://user-images.githubusercontent.com/18037362/135921691-424d2329-7491-4905-a67b-7f4667eb9af4.png)

**Comment by VanDavv** [comment]
@Erol444 please try again, this issue should be resolved now

**Comment by Erol444** [comment]
@VanDavv  works now, thanks!

**Comment by NiloofarSabouri** [comment]
I tried a lot now facing with this error...
How can I solve it?
Thanks

**Comment by Erol444** [comment]
@NiloofarSabouri  please provide full report and minimal repro example, so we can debug this locally.

**Comment by NiloofarSabouri** [comment]
sorry can you explain more. I don't understand what to do.
sincerely yours
N.Sabouri

**Comment by Erol444** [comment]
Hi @NiloofarSabouri , please follow docs on how to ask for support: https://docs.luxonis.com/en/latest/pages/support/
