### ISSUE TITLE
Can't reach "continue" button

### ISSUE THREAD

**Issue by Erol444** [luxonis/blobconverter#3]
On smaller screen sizes (eg laptop), you can't reach "continue" button after selection openvino version/model source. You have to zoom out so you can see the button and proceed to next steps. Solution would be to make the site scrollable or, preferably, make css so that it fits.
@cafemoloko  would you mind looking into this?

**Comment by cafemoloko** [comment]
Fixed by [this PR](https://github.com/luxonis/blobconverter/pull/6).
