### ISSUE TITLE
cannot convert model

### ISSUE THREAD

**Issue by k00shan** [luxonis/blobconverter#47]
Hi,
I used tensorflow object detection API to to fine-tune and train SSD MobileNet V1 FPN 640x640 with tensorflow 2.
Then using openvino I generated xml and bin file. But I cannot covert it to blob as it gives this error:
Cannot create NonMaxSuppression layer StatefulPartitionedCall/Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/non_max_suppression_with_scores/NonMaxSuppressionV5 id:2842 from unsupported opset: opset9

What can I do?

**Comment by FrancescoSaverioZuppichini** [comment]
Looks like an onnx related issue, what's your onnx version and which opset are you using?

**Comment by martinezger** [comment]
I have the same problem, working with Tensorflow 2, I can create the IR model but when I run the blobconverter I get this 
![image](https://user-images.githubusercontent.com/45072884/210778882-94a31f22-3374-4b28-b4bd-d19a28074d1a.png)

**Comment by Mario-arinapin** [comment]
Same issue, no onnx step, any fix to get it to blob?

**Comment by Whitchurch** [comment]
Zero support, after paying $200 for a Oak D Camera. Wow,

**Comment by Erol444** [comment]
@Thomas-C258 , @Mario-arinapin , @Whitchurch , @martinezger ; this is an issue with OpenVINO, best to create issue on their repo. Blobconverter is just a wrapper around complex OpenVINO tools (model optimizer, compile tool).

@Whitchurch if you aren't satisfied with the product, please do send an email to support@luxonis.com and we will refund you for the $200 device.

I'd also suggest trying different openvino verisons, and taking a look at our [official supported training notebooks](https://github.com/luxonis/[depthai-ml-training](https://github.com/luxonis/depthai-ml-training)).

**Comment by moradMIRO** [comment]
Is there anyone who could help me fix this problem? I am currently encountering the same issue and would greatly appreciate any assistance. Thank you in advance for your help

**Comment by Erol444** [comment]
@moradMIRO please see my comment above. If you are using a model from https://github.com/luxonis/depthai-ml-training and conversion doesn't work, please create an issue on that repo. Thanks!
