### ISSUE TITLE
Yet another TF conversion issue

### ISSUE THREAD

**Issue by trlmtr** [luxonis/blobconverter#48]
I am trying to convert TF frozen graph to blob using online blob converter. I am receiving message below. 

Error message

Command failed with exit code 1, command: /opt/intel/openvino2022_1/tools/compile_tool/compile_tool -m /tmp/blobconverter/600c78fcd1a541aa8d2ce540912eefd4/simple_frozen_graph/FP16/simple_frozen_graph.xml -o /tmp/blobconverter/600c78fcd1a541aa8d2ce540912eefd4/simple_frozen_graph/FP16/simple_frozen_graph.blob -c /tmp/blobconverter/600c78fcd1a541aa8d2ce540912eefd4/myriad_compile_config.txt -d MYRIAD -ip U8

Console output (stdout)

OpenVINO Runtime version ......... 2022.1.0
Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
Network inputs:
    x : u8 / [...]
Network outputs:
    Identity_1:0 : f16 / [...]
    Identity:0 : f16 / [...]

Error output (stderr)

Cannot get length of dynamic dimension

I would appreciate it if you advise what to do.

Best regards.
Tugrul

**Comment by Erol444** [comment]
Hi @trlmtr ,
Could you try the 2021.4 as well?
Thanks, Erik

**Comment by trlmtr** [comment]
Hi Erik,
Thank you very much for the reply. I tried the 2021.4 and I had more errors.
Please see descriptions below.

Command failed with exit code 1, command: /app/venvs/venv2021_4/bin/python /app/model_compiler/openvino_2021.4/converter.py --precisions FP16 --output_dir /tmp/blobconverter/45edc39111f64378a08208d1c0d9c48e --download_dir /tmp/blobconverter/45edc39111f64378a08208d1c0d9c48e --name simple_frozen_graph --model_root /tmp/blobconverter/45edc39111f64378a08208d1c0d9c48e

Console output (stdout)

========== Converting simple_frozen_graph to IR (FP16)
Conversion command: /app/venvs/venv2021_4/bin/python -m mo --framework=tf --data_type=FP16 --output_dir=/tmp/blobconverter/45edc39111f64378a08208d1c0d9c48e/simple_frozen_graph/FP16 --model_name=simple_frozen_graph --data_type=FP16 '--mean_values=[127.5,127.5,127.5]' '--scale_values=[255,255,255]' --input_model=/tmp/blobconverter/45edc39111f64378a08208d1c0d9c48e/simple_frozen_graph/FP16/simple_frozen_graph.pb

Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/tmp/blobconverter/45edc39111f64378a08208d1c0d9c48e/simple_frozen_graph/FP16/simple_frozen_graph.pb
	- Path for generated IR: 	/tmp/blobconverter/45edc39111f64378a08208d1c0d9c48e/simple_frozen_graph/FP16
	- IR output name: 	simple_frozen_graph
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	[127.5,127.5,127.5]
	- Scale values: 	[255,255,255]
	- Scale factor: 	Not specified
	- Precision of IR: 	FP16
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
[ WARNING ] Failed to import Inference Engine Python API in: PYTHONPATH
[ WARNING ] libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
[ WARNING ] Failed to import Inference Engine Python API in: /opt/intel/openvino2021_4/python/python3.8
[ WARNING ] libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
[ WARNING ] Could not find the Inference Engine Python API. At this moment, the Inference Engine dependency is not required, but will be required in future releases.
[ WARNING ] Consider building the Inference Engine Python API from sources or try to install OpenVINO (TM) Toolkit using "install_prerequisites.sh"
Model Optimizer version: 	2021.4.2-3974-e2a469a3450-releases/2021/4
FAILED:
simple_frozen_graph

Error output (stderr)

2023-02-06 15:11:56.746711: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/openvino2021_4/opencv/lib:/opt/intel/openvino2021_4/deployment_tools/ngraph/lib:/opt/intel/opencl:/opt/intel/openvino2021_4/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino2021_4/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino2021_4/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino2021_4/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino2021_4/deployment_tools/inference_engine/lib/intel64:
2023-02-06 15:11:56.746783: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[ ERROR ]  Shape [ -1 120 120   3] is not fully defined for output 0 of "x". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "x".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "x". 
 For more information please refer to Model Optimizer FAQ, question #40. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=40#question-40)
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Parameter.infer at 0x7faad2f4f790>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "x" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

Thanks  in advance.
Best regards.
Tugrul

**Comment by Erol444** [comment]
Hi @trlmtr , I think it would be useful to get the model files and architecture you have used, so we can debug this locally.  cc @tersekmatija 
Thanks, Erik

**Comment by trlmtr** [comment]
Hey @tersekmatija ,

I added  --input_shape=[1,120,120,3] and it successfully converted.

Thank you very much for the advise.

**Comment by tersekmatija** [comment]
Great to hear that, happy to help!

Closing as solved :)
