### ISSUE TITLE
Error when run docker-compose build?

### ISSUE THREAD

**Issue by huytuong010101** [luxonis/blobconverter#5]
After install and run Docker, I run docker-compose build as your guide but it raise an error:

=> CACHED [stage-1 10/16] RUN python3 -m pip install --upgrade tensorboa  0.0s
 => CACHED [stage-1 11/16] WORKDIR /app                                    0.0s
 => CACHED [stage-1 12/16] ADD requirements.txt .                          0.0s
 => ERROR [stage-1 13/16] ADD depthai/model_compiler depthai/model_compil  0.0s
------
 > [stage-1 13/16] ADD depthai/model_compiler depthai/model_compiler:
------
ERROR: Service 'api' failed to build

Can you help me fix this error?

**Comment by themarpe** [comment]
@huytuong010101 
Did you initialize submodules?
Execute the following and run docker-compose again afterwards
```
git submodule update --init --recursive
```

**Comment by huytuong010101** [comment]
thank u for your reply, i will try it

**Comment by VanDavv** [comment]
@huytuong010101 blobconverter has now model compiler added as a regular directory, not a submodule, so this issue should not occur anymore.
Will close the issue, but if you still have a trouble with it, feel free to circle back / reopen
