### ISSUE TITLE
Unable to convert .vino files into .blob files with the online converter tool 

### ISSUE THREAD

**Issue by Whitchurch** [luxonis/blobconverter#52]
Hello,
I downloaded .xml and .bin files, from the notebook:
https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/001-hello-world/model

I then tried to convert these .vino files using the online .blob converter and it failed with this error message:
Model file /tmp/blobconverter/a01bbd1648354a0cba721a7c41afb93b/v3-small_224_1/FP16/v3-small_224_1.xml cannot be opened!

I was able to load and run the .vino models in a python script to do classification and it worked.
Something is very wrong with the online converter, if it can't handle these .vino files directly from the .openvino website.

I am busy integrating vision into a robotics, project, i did not expect this Luxonis stack to be this troublesome. Really sad.

**Comment by Whitchurch** [comment]
[v3-small_224_1.0_float.zip](https://github.com/luxonis/blobconverter/files/11182142/v3-small_224_1.0_float.zip)

Here is the .zip file of the xml and .bin file

**Comment by Erol444** [comment]
Left my reply here: https://github.com/luxonis/blobconverter/issues/47#issuecomment-1500880727
