### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ahmed-gaal** [luxonis/blobconverter#54]
Hi.
I'm trying to convert a custom trained YOLOv8 model to Myriad X format for edge inference on OAK cameras. I converted the `.pt` model to `.onnx` format and got this error while running the conversion script:
`{
    "exit_code": 1,
    "message": "Command failed with exit code 1, command: /app/venvs/venv2022_1/bin/python /app/model_compiler/openvino_2022.1/converter.py --precisions FP16 --output_dir /tmp/blobconverter/969015cb9def47e5ae6af1ef9c91112b --download_dir /tmp/blobconverter/969015cb9def47e5ae6af1ef9c91112b --name latest --model_root /tmp/blobconverter/969015cb9def47e5ae6af1ef9c91112b",
    "stderr": "[ ERROR ]  -------------------------------------------------\n[ ERROR ]  ----------------- INTERNAL ERROR ----------------\n[ ERROR ]  Unexpected exception happened.\n[ ERROR ]  Please contact Model Optimizer developers and forward the following information:\n[ ERROR ]  While validating ONNX node '<Node(Slice): /model.22/Slice>':\nbad_weak_ptr\n[ ERROR ]  Traceback (most recent call last):\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py\", line 533, in main\n    ret_code = driver(argv)\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py\", line 489, in driver\n    graph, ngraph_function = prepare_ir(argv)\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py\", line 394, in prepare_ir\n    ngraph_function = moc_pipeline(argv, moc_front_end)\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/moc_frontend/pipeline.py\", line 147, in moc_pipeline\n    ngraph_function = moc_front_end.convert(input_model)\nRuntimeError: While validating ONNX node '<Node(Slice): /model.22/Slice>':\nbad_weak_ptr\n\n[ ERROR ]  ---------------- END OF BUG REPORT --------------\n[ ERROR ]  -------------------------------------------------\n",
    "stdout": "========== Converting latest to IR (FP16)\nConversion command: /app/venvs/venv2022_1/bin/python -- /app/venvs/venv2022_1/bin/mo --framework=onnx --data_type=FP16 --output_dir=/tmp/blobconverter/969015cb9def47e5ae6af1ef9c91112b/latest/FP16 --model_name=latest --input= '--mean_values=[127.5,127.5,127.5]' '--scale_values=[255,255,255]' --data_type=FP16 --input_model=/tmp/blobconverter/969015cb9def47e5ae6af1ef9c91112b/latest/FP16/latest.onnx\n\nModel Optimizer arguments:\nCommon parameters:\n\t- Path to the Input Model: \t/tmp/blobconverter/969015cb9def47e5ae6af1ef9c91112b/latest/FP16/latest.onnx\n\t- Path for generated IR: \t/tmp/blobconverter/969015cb9def47e5ae6af1ef9c91112b/latest/FP16\n\t- IR output name: \tlatest\n\t- Log level: \tERROR\n\t- Batch: \tNot specified, inherited from the model\n\t- Input layers: \tNot specified, inherited from the model\n\t- Output layers: \tNot specified, inherited from the model\n\t- Input shapes: \tNot specified, inherited from the model\n\t- Source layout: \tNot specified\n\t- Target layout: \tNot specified\n\t- Layout: \tNot specified\n\t- Mean values: \t[127.5,127.5,127.5]\n\t- Scale values: \t[255,255,255]\n\t- Scale factor: \tNot specified\n\t- Precision of IR: \tFP16\n\t- Enable fusing: \tTrue\n\t- User transformations: \tNot specified\n\t- Reverse input channels: \tFalse\n\t- Enable IR generation for fixed input shape: \tFalse\n\t- Use the transformations config file: \tNone\nAdvanced parameters:\n\t- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: \tFalse\n\t- Force the usage of new Frontend of Model Optimizer for model conversion into IR: \tFalse\nOpenVINO runtime found in: \t/opt/intel/openvino2022_1/python/python3.8/openvino\nOpenVINO runtime version: \t2022.1.0-7019-cdb9bec7210-releases/2022/1\nModel Optimizer version: \t2022.1.0-7019-cdb9bec7210-releases/2022/1\n[WARN] 2023-05-25T09:00:19z frontends/onnx/frontend/src/ops_bridge.cpp 240\tCurrently ONNX operator set version: 17 is unsupported. Falling back to: 15\nFAILED:\nlatest\n"
}`

**Comment by HonzaCuhel** [comment]
Closing due to the inactivity. If anything comes up, feel free to reopen the issue.
