### ISSUE TITLE
\n[ ERROR ]  While validating ONNX node '<Node(Concat): /roi_heads/box_pooler/Concat_2>':\nCheck 'concat_axis < this_input_rank.get_length() && concat_axis >= 0'

### ISSUE THREAD

**Issue by venumasini777** [luxonis/blobconverter#57]
Hi,

I tried to convert my pretrained detectron2 model to blob format for inference which is used for Instance Segmentation.

Initially converted the detectron2 pytorch model to torchscript format using the following lines:

            wrapper= TracingAdapter(model, example, inference_func)
            wrapper.eval()
            traced_script_module= torch.jit.trace(wrapper, (example,))

Then converted the traced_script_module to onnx format using:

            !pip install onnx
            # Save the TorchScript model to an ONNX file
            onnx_file = "detectron2_model.onnx"
            torch.onnx.export(
                traced_script_module,
                example,
                onnx_file,
                export_params=True,
                opset_version=11,  # Choose the desired ONNX opset version
                do_constant_folding=True,
                input_names=["input"],  # Set the names for input and output nodes
                output_names=["output"],
                dynamic_axes={"input": {0: "batch_size"}, "output": {0: "batch_size"}},
            )

Then tried to convert the onnx model to blob format using:

import blobconverter

blob_path = blobconverter.from_onnx(
    model="/content/drive/MyDrive/ComputerVision/detectron2_model.onnx",
    data_type="FP32",
    shaves=5,
)

And got the below Error Report. I'm not sure whether the layers in the model are not supported for conversion or is there any other issue with the model.

\n[ ERROR ]  ----------------- INTERNAL ERROR ----------------\n[ ERROR ]  Unexpected exception happened.\n[ ERROR ]  Please contact Model Optimizer developers and forward the following information:\n[ ERROR ]  While validating ONNX node '<Node(Concat): /roi_heads/box_pooler/Concat_2>':\nCheck 'concat_axis < this_input_rank.get_length() && concat_axis >= 0' failed at core/src/op/concat.cpp:50:\nWhile validating node 'v0::Concat Concat_9882 (/roi_heads/box_pooler/Constant_6_output_0[0]:i64{1}, /roi_heads/box_pooler/Split_output_0[0]:i64{1}, /roi_heads/box_pooler/Constant_7_output_0[0]:i64{}) -> (dynamic...)' with friendly_name 'Concat_9882':\nConcatenation axis (0) is out of bounds [0, -1] for argument 2, which has shape {}.\n\n[ ERROR ]  Traceback (most recent call last):\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py\", line 533, in main\n    ret_code = driver(argv)\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py\", line 489, in driver\n    graph, ngraph_function = prepare_ir(argv)\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/main.py\", line 394, in prepare_ir\n    ngraph_function = moc_pipeline(argv, moc_front_end)\n  File \"/app/venvs/venv2022_1/lib/python3.8/site-packages/openvino/tools/mo/moc_frontend/pipeline.py\", line 147, in moc_pipeline\n    ngraph_function = moc_front_end.convert(input_model)\nRuntimeError: While validating ONNX node '<Node(Concat): /roi_heads/box_pooler/Concat_2>':\nCheck 'concat_axis < this_input_rank.get_length() && concat_axis >= 0' failed at core/src/op/concat.cpp:50:\nWhile validating node 'v0::Concat Concat_9882 (/roi_heads/box_pooler/Constant_6_output_0[0]:i64{1}, /roi_heads/box_pooler/Split_output_0[0]:i64{1}, /roi_heads/box_pooler/Constant_7_output_0[0]:i64{}) -> (dynamic...)' with friendly_name 'Concat_9882':\nConcatenation axis (0) is out of bounds [0, -1] for argument 2, which has shape {}.\n\n\n[ ERROR ]  ---------------- END OF BUG REPORT --------------\n[ ERROR ]  -------------------------------------------------\n",

**Comment by Erol444** [comment]
Hi @venumasini777 ,
This is an OpenVINO issue: `Concatenation axis (0) is out of bounds [0, -1] for argument 2, which has shape {}.`, so I would suggest opening an issue on the OpenVINO repository.

**Comment by danielafrimi** [comment]
any news with that? trying to compile yolo model and gets the same error

thanks

**Comment by Erol444** [comment]
Hi @danielafrimi , copy-pasting;

**Note**: Blobconverter is a simple wrapper around the OpenVINO tools, specifically:
- Model optimizer: https://docs.openvino.ai/2021.4/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html
- Compile tool: https://docs.openvino.ai/2021.4/openvino_inference_engine_tools_compile_tool_README.html

Most of the time, if the blobconverter returns an error, it's an **error thrown by Model Optimizer / Compile tool, NOT by blobconverter itself**. So please
don't report such issues here, but on OpenVINO github: https://github.com/openvinotoolkit/openvino

For converting model to blob, see documentation here: https://docs.luxonis.com/en/latest/pages/model_conversion/
