### ISSUE TITLE
Conversion Error: Unsupported layer type "HardSigmoid"

### ISSUE THREAD

**Issue by CometTD** [luxonis/blobconverter#63]
I tried to convert onnx to blob. 
![41L@3$BVP$1(`%I~7NAI}4B](https://github.com/luxonis/blobconverter/assets/48607868/4d0b6524-5b09-4244-9c00-8cc357d59c6d)
Can it be updated to support HardSigmoid?

**Comment by Erol444** [comment]
Hi @CometTD ,
We apologize for the late reply. This layer depends on the OpenVINO support for the VPU (Myriad X), copy/pasting the docs on it:

**Note**: Blobconverter is a simple wrapper around the OpenVINO tools, specifically:
- Model optimizer: https://docs.openvino.ai/2021.4/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html
- Compile tool: https://docs.openvino.ai/2021.4/openvino_inference_engine_tools_compile_tool_README.html

Most of the time, if the blobconverter returns an error, it's an **error thrown by Model Optimizer / Compile tool, NOT by blobconverter itself**. So please
don't report such issues here, but on OpenVINO github: https://github.com/openvinotoolkit/openvino

For converting model to blob, see documentation here: https://docs.luxonis.com/en/latest/pages/model_conversion/

I hope this helps.
Thanks, Erik

**Comment by HonzaCuhel** [comment]
Hi @CometTD,

we have encountered this problem as well and managed to find a workaround by defining a custom HardSigmoid layer and replacing the `nn.Hardsigmoid()` with the custom one. Here's a simple [dummy example](https://colab.research.google.com/drive/1WOqHjPjSU7sBXI4TMnZZV0WFgFT2jwga?usp=sharing).

To replace the `nn.Hardsigmoid()` with the custom one, you should be able to use this code:
```python
import torch
import torch.nn.functional as F
import torch.nn as nn

def hard_sigmoid(x, inplace=False):
    return F.relu6(x + 3, inplace) / 6

class HS(torch.nn.Module):
    def forward(self, x):
        return hard_sigmoid(x)

# Replace
def replace_relu_with_relu6(model):
    for name, module in model.named_children():
        if isinstance(module, nn.Hardsigmoid):
            setattr(model, name, HS())
            print('Replacing Hardsigmoid')
```

Kind regards,
Jan

**Comment by HonzaCuhel** [comment]
Closing due to the inactivity. If anything comes up, feel free to reopen the issue.
