### ISSUE TITLE
Requested output shape {5,1,3,480,640} is incompatible with input shape {1,3,480,640}

### ISSUE THREAD

**Issue by gr8-98** [luxonis/blobconverter#67]
Hi, I tried to convert an onnx model to blob file, but I got this type of error:
<img width="392" alt="image" src="https://github.com/luxonis/blobconverter/assets/61749850/7187d5f5-9a29-4afc-aa03-0b4f506b06fe">
Could you help me to solve this problem?

**Comment by tersekmatija** [comment]
It seems you use a some tensors with rank 5 in your model, which could be causing those issues. Could you share .xml or .onnx file and we can take a look? @GretaCorti

**Comment by GretaCorti** [comment]
I'm waiting for a response from my boss about sharing the onnx model with you @tersekmatija 
Meanwhile, I can tell you that the onnx model requires an input of size (5, 480, 640, 3) because it needs 5 images.
However, i do not understand why the error mentions an output of shape (5,1,3,480,680).

**Comment by GretaCorti** [comment]
@tersekmatija, you can find the model here: [model.onnx](https://polimi365-my.sharepoint.com/:u:/g/personal/10598667_polimi_it/EfgRJCP-rDpJtei9BmEuEXEBk0cLutYpRWOrlhmc9wwNUw?e=KuBKGg)

**Comment by tersekmatija** [comment]
Thanks, it seems that the model is quite complex. Can you try to modify it such that you feed in 5 inputs separately? In other words, please try to refine the model such that you feed in 5 x [1, 3, 480, 640] instead of [5, 3, 480, 640]. This should help the compiler with inferring the shape.

**Comment by gr8-98** [comment]
Thank you very much, @tersekmatija. This strategy solved the problem.

**Comment by tersekmatija** [comment]
Happy to hear that @gr8-98! I'll close the issue. Feel free to re-open if other issues arise.
