### ISSUE TITLE
URL was not found on the server

### ISSUE THREAD

**Issue by IsRaTiAlv** [luxonis/blobconverter#7]
_The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again._
When following the port 0.0.0.0:8080 

It would be great more information about the requirements and steps to convert the models.

**Comment by VanDavv** [comment]
Hi @IsRaTiAlv , the version on http://luxonis.com:8080 was depreciated. It used an old version of openvino. We have now updated the converter and released a [blobconverter PyPi package](https://pypi.org/project/blobconverter/), that makes blob converting easier.

But if you'd like to still use the old one, it is still deployed under http://69.164.214.171:8085/, so if you'd like to postpone the transition to the new blobconverter, just update the URL to this one.

**Comment by VanDavv** [comment]
Feel free to reopen for further assistance
