### ISSUE TITLE
Error while converting .pb file into .blob

### ISSUE THREAD

**Issue by rafal-mazur** [luxonis/blobconverter#76]
Hello,

I'm trying to convert my .pb file to .blob to deploy it on OAK-1 lite device. The online blob converter thowrs the error

> Error message
> Command failed with exit code 1, command: /opt/intel/openvino2022_1/tools/compile_tool/compile_tool -m /tmp/blobconverter/608bbf1ef5db4445a806b913d712dcdb/ctpn/FP16/ctpn.xml -o /tmp/blobconverter/608bbf1ef5db4445a806b913d712dcdb/ctpn/FP16/ctpn.blob -c /tmp/blobconverter/608bbf1ef5db4445a806b913d712dcdb/myriad_compile_config.txt -d MYRIAD -ip U8
>
> Console output (stdout)
> OpenVINO Runtime version ......... 2022.1.0
> Build ........... 2022.1.0-7019-cdb9bec7210-releases/2022/1
> Network inputs:
>     Placeholder : u8 / [...]
> Network outputs:
>     Reshape_2:0 : f16 / [...]
>     rpn_bbox_pred/Reshape_1:0 : f16 / [...]
> Error output (stderr)
>
> Cannot get length of dynamic dimension

Parameters in converter:
**Model optimizer params:**
`--data_type=FP16 --mean_values=[127.5,127.5,127.5] --scale_values=[255,255,255]` (default)
**Compile parameters:**
`-ip U8` (default)

Error occurs on any number of shaves chosen.

I'm new to oak openvino etc. so could someone explain if I'm doing something wrong or what to change?

**Comment by klemen1999** [comment]
Hi @rafal-mazur , it seems like it is the same issue as with #48 . Can you try specifying input shape when converting?

**Comment by rafal-mazur** [comment]
Hi, I included `--input_shape [1,512,512,3]` parameter as in the #48. Thanks a lot for support :)
